from .dymaxion import DymaxionProjection
from . import rotations, conversions, utilities

# Load git autogenerated version - update with setup.py update_version
from ._version import __version__

__all__ = ['DymaxionProjection', '__version__', 'rotations', 'conversions', 'utilities']
